let events = [
    { img: "img/1.jpg", title: "𝗨𝗦𝗣𝗗-𝗦𝗖𝗖 𝗖𝗼𝗰𝗼𝗻𝘂𝘁 𝗩𝗮𝗹𝘂𝗲 𝗖𝗵𝗮𝗶𝗻 𝗙𝗶𝗻𝗮𝗻𝗰𝗶𝗻𝗴 𝗟𝗮𝘂𝗻𝗰𝗵𝗶𝗻𝗴", description: "USPD Savings and Credit Cooperative held its launching of its newly formulated loans and savings package, the 𝗖𝗼𝗰𝗼𝗻𝘂𝘁 𝗩𝗮𝗹𝘂𝗲 𝗖𝗵𝗮𝗶𝗻 𝗙𝗶𝗻𝗮𝗻𝗰𝗶𝗻𝗴, at the Padada Gymnasium, last October 30, 2024. This financing initiative supports improvement of productivity of coconut value actors, including coconut farm workers, tillers and farmers, traders and entrepreneurs. ", images: ["img/2.jpg", "img/3.jpg", "img/4.jpg", "img/5.jpg", "img/11.jpg", "img/12.jpg", "img/13.jpg"] },
    { img: "img/news2.jpg", title: "🎉 What an Amazing Day at the 3rd FOCCUS PEARLS OLYMPICS 2024! 🎉", description: "On October 12, 2024, we gathered at the Brokenshire Hotel-Resort and Convention Center to celebrate unity, cooperation, and the spirit of sportsmanship! As we marked International Credit Union Day and Cooperative Month, the 3rd FOCCUS PEARLS Olympics was a vibrant testament to our strong community.", images: ["img/news2.1.jpg", "img/news2.2.jpg", "img/news2.3.jpg"] },
    { img: "img/news3.jpg", title: "𝗠𝗢𝗔 𝗦𝗶𝗴𝗻𝗶𝗻𝗴 between 𝗔𝘁𝗲𝗻𝗲𝗼 𝗱𝗲 𝗗𝗮𝘃𝗮𝗼 𝗨𝗻𝗶𝘃𝗲𝗿𝘀𝗶𝘁𝘆 and 𝗠𝗼𝗱𝗲𝗹 𝗖𝗼𝗼𝗽𝗲𝗿𝗮𝘁𝗶𝘃𝗲 𝗡𝗲𝘁𝘄𝗼𝗿𝗸", description: "𝗔𝘁𝗲𝗻𝗲𝗼 𝗱𝗲 𝗗𝗮𝘃𝗮𝗼 𝗖𝗼𝗳𝗳𝗲𝗲 𝗮𝗻𝗱 𝗖𝗮𝗰𝗮𝗼 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗟𝗮𝗯𝗼𝗿𝗮𝘁𝗼𝗿𝘆 (ADDC3LL) is a collaborative project of Ateneo de Davao Univeristy (AdDU) and Model Cooperative Network (MCN), under its special project 3VC SPADe. Through collaborative research and learning activities with local coffee and cacao producers, ADDC3LL aims to empower them with scientific knowledge and methodologies. By applying a scientific approach to their daily coffee and cacao processing practices, producers can potentially elevate the quality of their produce.", images: ["img/news3.1.jpg", "img/news3.2.jpg", "img/news3.3.jpg"] },
    { img: "img/news4.jpg", title: "Champions for coffee excellence in cooperatives.", description: "The Q grading certification program is one of the initiatives of MCN’s 3VC (Viable Cooperatives, Vibrant Communities participating in and benefitting from agri Value Chains) project supported by the European Union and the German Federal Ministry for Economic Cooperation and Development through the Deutsche Gesellschaft für Internationale Zusammenarbeit.", images: ["img/news4.1.jpg", "img/news4.2.jpg", "img/news4.3.jpg"] },
    { img: "img/news5.jpg", title: "From Start-Up to Stand-Out! ", description: "Excited to highlight the amazing progress of our WeLEAD and COOP TECH start-ups! With support from MCN and AdDVentures, they've demonstrated dedication and creativity, leading to a successful presentation yesterday.", images: ["img/news5.1.jpg", "img/news5.2.jpg", "img/news5.3.jpg"] },
    { img: "img/news6.jpg", title: "AFA, AgriCOOPh, BDA, Coop-NATCCO, CSA, MASS-SPECC, PFCCO-ML, PhilDHRRA, XAESFI, and PAKISAMA", description: "Great discussions and insights were shared among our valued SPADe Implementing Partners (AFA, AgriCOOPh, BDA, Coop-NATCCO, CSA, MASS-SPECC, PFCCO-ML, PhilDHRRA, XAESFI, and PAKISAMA) during the GIZ SPADe-ImPas 2nd Coordination Meeting as we continue to work towards strengthening the implementation of regional and local peace and development agendas in Mindanao through the SPADe project, co-funded by the European Union and GIZ.", images: ["img/news6.1.jpg", "img/news6.2.jpg", "img/news6.3.jpg"] },
    { img: "img/news7.jpg", title: "The Cooperative Development Authority XI", description: "Model Cooperative Network (MCN) and MAGSIGE Multipurpose Cooperative meets with students from the School of Social Innovation Business of Hanshin University at the Library Café by Coop Cups.This encounter discusses how cooperatives continue to be a force for inclusive economic growth in many areas in the Philippines while operating as a social enterprise that is collectively owned and controlled by its members. The Korean delegation is accompanied and supported by Camp Asia Philippines and the Korean International Cooperation Agency.", images: ["img/news7.1.jpg", "img/news7.2.jpg", "img/news7.3.jpg"] },
    { img: "img/news8.jpg", title: "Sensory skills activated! ☕", description: "Heartfelt gratitude to Filipino Coffee Institute (FCI) for enhancing the sensory skills of the participants from different organizations and institutions--Bacofa Cooperative, MAGROW Multi Purpose Cooperative, Model Cooperative Network, and volunteers from Davao del Sur State College (DSSC), Lil' Ben Coffee & Convenience , Lot 38 Kape. Bukid. Frappe and Ateneo de Davao University - School of Engineering and Architecture, during the Three-Day In-Depth Coffee Sensory Skills Training (Dec. 20-22, 2023) in Mt. Apo Highland Resort, Kapatagan, Davao del Sur.", images: ["img/news8.1.jpg", "img/news8.2.jpg", "img/news8.3.jpg"] },
    { img: "img/news9.jpg", title: "Way to go, Incubatees!", description: "We are delighted to share the highlights of the WeLEAD and CoopTECH incubation programs. The said activities are part of the WeLEAD and CoopTECH Business incubation of MCN's SPADe project, supported by the European Union and the German Federal Ministry for Economic Cooperation and Development, in partnership with Ateneo de Davao University's AdDVentures.", images: ["img/news9.1.jpg", "img/news9.2.jpg", "img/news9.3.jpg"] },
    { img: "img/news10.jpg", title: "Visit the BACOFA booth at the GMall of Digos", description: "Thank you for gracing the BACOFA booth and sampling the BACOFA Winners Circle Coffee Collection, Gov. Yvonne R. Cagas of Davao del Sur! Visit the BACOFA booth at the GMall of Digos and celebrate the Coffee Fiesta Davao del Sur with BACOFA Cooperative and Specialty Coffee Depot PH.", images: ["img/news10.1.jpg", "img/news10.2.jpg", "img/news10.3.jpg"] },
    { img: "img/news11.jpg", title: "MCN Federation joins the Cooperative Day with the President at the Malacañang Palace today, October 16, 2023.", description: "Representing the federation are Dir. Jerson Remo and CEO Rhoda Ruth Pillerin.", images: ["img/news11.1.jpg", "img/news11.2.jpg", "img/news11.3.jpg"] },
    { img: "img/news12.jpg", title: "We extend our gratitude and congratulations to the Women Leading in Enterprise and Agriculture Development and Technology (WeLEAD)", description: "We extend our gratitude and congratulations to the Women Leading in Enterprise and Agriculture Development and Technology (WeLEAD)  and the Innovation Enhancement in Cooperatives-Developing Young Innovators (CoopTECH) incubatees and mentors for their active participation and contribution during the start-up groups and mentors meet-up as well as the Demand and Supply Training workshop.", images: ["img/news12.1.jpg", "img/news12.2.jpg", "img/news12.3.jpg"] },
    { img: "img/news13.jpg", title: "Happening Now:", description: "WeLEAD and CoopTECH Business incubatees of MCN's SPADe project supported by the European Union and the German Federal Ministry for Economic Cooperation and Development, in partnership with Ateneo de Davao University's AdDVentures, are currently having their Demand and Supply Training workshop at the ADDU's CCFC Bldg. Media Room.", images: ["img/news13.1.jpg", "img/news13.2.jpg", "img/news13.3.jpg"] },
    { img: "img/news14.jpg", title: "MCN member cooperatives participate in the Trade Fair & Exhibit", description: "MCN member cooperatives participate in the Trade Fair & Exhibit at the NCCC Mall VP, Davao City in celebration of the Cooperative Month 2023", images: ["img/news14.1.jpg", "img/news14.2.jpg", "img/news14.3.jpg"] },
    { img: "img/news15.jpg", title: "Morning well spent at Coop Cups☕", description: "We would like to extend our gratitude to our valued guests from the media world: Joric Adventures, Davao Food Blog, Ma'am Tere Nierna of DDC, and Ma'am Nova Mae Francas from Mindanao Times. Also, the presence of the BACOFA coffee producers with the Philippine Coffee Quality Competition's (PCQC) 2nd placer in Arabica coffee, Mr. John Lawrence Dela Cerna as well as Mr. Elmar Limpiado of Craft Coffee-Roastery last Wednesday, September 13, 2023, at the Library Café by Coop Cups in Davao City.", images: ["img/news15.1.jpg", "img/news15.2.jpg", "img/news15.3.jpg"] },
    { img: "img/news16.jpg", title: "INTRODUCTION TO COOPERATIVE SUCCESSION & LUZON OWNERSHIP MEETING 2023", description: "", images: ["img/news16.1.jpg", "img/news16.2.jpg", "img/news16.jpg"] },
    { img: "img/news17.jpg", title: "HAPPENING NOW: Exposure & Study Visit on Financial Inclusion in Southeast Asia 🇵🇭🇹🇭", description: "Co-ops in the Model Cooperative Network staying true to their core as they deepen their understanding on financial inclusion.", images: ["img/news17.1.jpg", "img/news17.2.jpg", "img/news17.3.jpg"] },
    { img: "img/news18.jpg", title: "HAPPENING NOW: CU-TE Trainors’ Training Batch 27", description: "Empowering cooperatives by nurturing the next line of cooperative trainers and creating a new generation of advocates of the Model Cooperative Building (MCB) Methodology. 💡💡💡", images: ["img/news18.1.jpg", "img/news18.2.jpg", "img/news18.3.jpg"] },
    { img: "img/news19.jpg", title: "Davao City Homesite and Housing Multipurpose Cooperative (DCHH MPC)", description: "Thank you to our partner cooperatives under the FOCCUS Network for the support during the Grand Opening of The Library Cafe by Co-op Cups!", images: ["img/news19.1.jpg", "img/news19.2.jpg", "img/news19.3.jpg"] },
    { img: "img/news20.jpg", title: "Model Cooperative Network was achieved last June 8 during the groundbreaking ceremony", description: "Another milestone for Model Cooperative Network was achieved last June 8 during the groundbreaking ceremony of their soon-to-rise building in Juna Subd., Matina, Davao City. This 3-storey building will have its own commercial spaces on the first floor, MCN office on the second floor, and training center on the third floor.", images: ["img/news20.1.jpg", "img/news20.2.jpg", "img/news20.3.jpg"] },
    { img: "img/news21.jpg", title: "The Model Cooperative Network celebrated its hybrid 17th Annual General Assembly", description: "The Model Cooperative Network celebrated its hybrid 17th Annual General Assembly, on-site at Dusit Thani, Davao City and online via Zoom, last May 14, 2022. A remarkable convivial event of camaraderie and diversity in pounding pavement towards success, for a safe, sound, and sustainable future.", images: ["img/news21.1.jpg", "img/news21.2.jpg", "img/news21.3.jpg"] },
];  
let currentThumbIndex = 0;
function renderEvents() {
    let eventGrid = document.getElementById("eventGrid");
    eventGrid.innerHTML = "";
    events.forEach((event, index) => {
        eventGrid.innerHTML += `
            <div class="event-card">
                <img src="${event.img}" alt="${event.title}">
                <h4>${event.title}</h4>
                <button class="see-more" onclick="updateMainEvent(${index})">See More</button>
            </div>
        `;
    });
}
function updateMainEvent(index) {
    let event = events[index];
    document.getElementById("mainSlider").style.display = "none";
    document.getElementById("eventDetails").style.display = "flex";
    document.getElementById("mainImage").src = event.img;
    document.getElementById("mainTitle").textContent = event.title;
    document.getElementById("mainDescription").textContent = event.description;
    renderThumbnails(event.images);

    window.scrollTo({ top: 0, behavior: 'smooth' });
}
function renderThumbnails(images) {
    let thumbnails = document.getElementById("thumbnails");
    thumbnails.innerHTML = images.slice(currentThumbIndex, currentThumbIndex + 3).map(img => `<img class='thumbnail' src='${img}' onclick='changeMainImage("${img}")'>`).join('');
}
function changeMainImage(src) {
    document.getElementById("mainImage").src = src;
}
renderEvents();